export const kathmanduPlaces = {
  "Anamnagar": ["New Baneshwor", "Maitidevi", "Dillibazar", "Ghattekulo"],
  "Bagbazar": ["Ratopul", "New Road", "Sundhara", "Chhetrapati"],
  "Balaju": ["Gongabu", "Sitapaila", "Swayambhu", "Thankot"],
  "Baluwatar": ["Lazimpat", "Maharajgunj", "Dhumbarahi", "Naxal"],
  "Baneshwor": ["New Baneshwor", "Tinkune", "Maitidevi", "Koteshwor"],
  "Bansbari": ["Maharajgunj", "Dhapasi", "Budanilkantha", "Baluwatar"],
  "Basantapur": ["New Road", "Sundhara", "Chhetrapati", "Paknajol"],
  "Bhaisepati": ["Nakkhu", "Sanepa", "Jawalakhel", "Patan"],
  "Bhaktapur": ["Kausaltar", "Imadol", "Lubhu", "Pepsicola"],
  "Bhimsengola": ["New Baneshwor", "Tinkune", "Jadibuti", "Koteshwor"],
  "Boudha": ["Chabahil", "Jorpati", "Sukedhara", "Gokarna"],
  "Budanilkantha": ["Bansbari", "Kapan", "Dhapasi", "Tokha"],
  "Chabahil": ["Gaushala", "Boudha", "Dhumbarahi", "Sukedhara"],
  "Chhauni": ["Swayambhu", "Sitapaila", "Dallu", "Teku"],
  "Chhetrapati": ["Paknajol", "Thamel", "New Road", "Basantapur"],
  "Dallu": ["Sitapaila", "Chhauni", "Swayambhu", "Teku"],
  "Dhapasi": ["Tokha", "Bansbari", "Gongabu", "Budanilkantha"],
  "Dillibazar": ["Maitidevi", "Ghattekulo", "Anamnagar", "Ratopul"],
  "Dobi Ghat": ["Sanepa", "Jawalakhel", "Pulchowk", "Manbhawan"],
  "Dhumbarahi": ["Chabahil", "Baluwatar", "Sukedhara", "Maharajgunj"],
  "Gaushala": ["Sinamangal", "Chabahil", "Ghattekulo", "Maitidevi"],
  "Ghattekulo": ["Dillibazar", "Maitidevi", "Anamnagar", "Gaushala"],
  "Gongabu": ["Balaju", "Tokha", "Samakhusi", "Dhapasi"],
  "Gyaneshwor": ["Maitidevi", "Dillibazar", "Naxal", "Ratopul"],
  "Hattiban": ["Bhaisepati", "Godawari", "Nakkhu", "Satdobato"],
  "Hattisar": ["Naxal", "Lazimpat", "Gyaneshwor", "Baluwatar"],
  "Imadol": ["Lubhu", "Gwarko", "Koteshwor", "Bhaktapur"],
  "Jadibuti": ["Tinkune", "Koteshwor", "Pepsicola", "Bhimsengola"],
  "Jamal": ["Ratopul", "New Road", "Sundhara", "Chhetrapati"],
  "Jawalakhel": ["Pulchowk", "Sanepa", "Manbhawan", "Patan"],
  "Kalanki": ["Thankot", "Teku", "Sitapaila", "Kalimati"],
  "Kalopul": ["Dhumbarahi", "Sukedhara", "Chabahil", "Baluwatar"],
  "Kalimati": ["Teku", "Kalanki", "Tripureshwor", "Chhauni"],
  "Kapan": ["Budanilkantha", "Boudha", "Gokarna", "Sundarijal"],
  "Kausaltar": ["Bhaktapur", "Jadibuti", "Koteshwor", "Imadol"],
  "Kirtipur": ["Chobhar", "Kalanki", "Thankot", "Swayambhu"],
  "Koteshwor": ["Jadibuti", "Kausaltar", "Imadol", "New Baneshwor"],
  "Kupandole": ["Pulchowk", "Sanepa", "Jawalakhel", "Manbhawan"],
  "Lalitpur": ["Pulchowk", "Jawalakhel", "Manbhawan", "Sanepa"],
  "Lazimpat": ["Baluwatar", "Hattisar", "Maharajgunj", "Naxal"],
  "Lubhu": ["Imadol", "Gwarko", "Tikathali", "Bhaktapur"],
  "Maitidevi": ["Dillibazar", "Anamnagar", "Ghattekulo", "Gyaneshwor"],
  "Maitighar": ["Thapathali", "New Baneshwor", "Tripureshwor", "Ratopul"],
  "Maharajgunj": ["Bansbari", "Baluwatar", "Dhumbarahi", "Lazimpat"],
  "Manbhawan": ["Jawalakhel", "Pulchowk", "Dobi Ghat", "Patan"],
  "Nakkhu": ["Bhaisepati", "Hattiban", "Sanepa", "Jawalakhel"],
  "Narayanhiti": ["Lazimpat", "Hattisar", "Jamal", "New Road"],
  "Naxal": ["Gyaneshwor", "Lazimpat", "Hattisar", "Maitidevi"],
  "New Baneshwor": ["Baneshwor", "Tinkune", "Maitidevi", "Anamnagar"],
  "New Road": ["Basantapur", "Sundhara", "Chhetrapati", "Jamal"],
  "Paknajol": ["Thamel", "Chhetrapati", "Swayambhu", "Sitapaila"],
  "Patan": ["Jawalakhel", "Manbhawan", "Pulchowk", "Gwarko"],
  "Pepsicola": ["Jadibuti", "Kausaltar", "Koteshwor", "Bhaktapur"],
  "Pulchowk": ["Jawalakhel", "Manbhawan", "Kupandole", "Patan"],
  "Ratopul": ["Gaushala", "Ghattekulo", "Gyaneshwor", "Maitidevi", "Bagbazar"],
  "Samakhusi": ["Gongabu", "Balaju", "Swayambhu", "Tokha"],
  "Sanepa": ["Pulchowk", "Jawalakhel", "Dobi Ghat", "Nakkhu"],
  "Sankhamul": ["Thapagaun", "New Baneshwor", "Maitighar", "Koteshwor"],
  "Sinamangal": ["Gaushala", "Tinkune", "Jadibuti", "Bhimsengola"],
  "Sitapaila": ["Balaju", "Swayambhu", "Chhauni", "Dallu"],
  "Sukedhara": ["Chabahil", "Dhumbarahi", "Kalopul", "Gongabu"],
  "Sundhara": ["New Road", "Basantapur", "Tripureshwor", "Jamal"],
  "Swayambhu": ["Chhauni", "Sitapaila", "Balaju", "Paknajol"],
  "Tangal": ["Lazimpat", "Baluwatar", "Naxal", "Hattisar"],
  "Teku": ["Tripureshwor", "Kalimati", "Dallu", "Chhauni"],
  "Thankot": ["Kalanki", "Balaju", "Kirtipur", "Sitapaila"],
  "Thapagaun": ["New Baneshwor", "Sankhamul", "Tinkune", "Maitighar"],
  "Thapathali": ["Tripureshwor", "Maitighar", "Teku", "Kalopul"],
  "Thamel": ["Chhetrapati", "Paknajol", "New Road", "Lazimpat"],
  "Tokha": ["Gongabu", "Dhapasi", "Budanilkantha", "Samakhusi"],
  "Tripureshwor": ["Sundhara", "Teku", "Thapathali", "Kalimati"],
  "Tinkune": ["Jadibuti", "New Baneshwor", "Bhimsengola", "Sinamangal"],
};